src/takamatsu_tatsumi/beans/Post.java
package takamatsu_tatsumi.beans;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Post implements Serializable {
	private int id;
	private String title;
	private String text;
	private String category;
	private String writterName;
	private int writterId;
	private boolean isDelete;
	private Date createdDate;
	private List<Comment> comments;

	public Post() {

	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getWritterName() {
		return writterName;
	}
	public void setWritterName(String writterName) {
		this.writterName = writterName;
	}
	public int getWritterId() {
		return writterId;
	}
	public void setWritterId(int writterId) {
		this.writterId = writterId;
	}
	public boolean isDelete() {
		return isDelete;
	}
	public void setDelete(boolean isDelete) {
		this.isDelete = isDelete;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public List<Comment> getComments() {
		return comments;
	}
	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}
}

src/takamatsu_tatsumi/controllor/HomeServlet.java
package takamatsu_tatsumi.controllor;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import takamatsu_tatsumi.beans.Post;
import takamatsu_tatsumi.beans.User;
import takamatsu_tatsumi.service.PostService;

@WebServlet(urlPatterns = {"/home"})
public class HomeServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		this.doPost(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		List<Post> postList = new PostService().getPostList();
		HttpSession session = request.getSession();
		User loginUser = (User) session.getAttribute("loginUser");
		if(loginUser != null) {
			request.setAttribute("postList", postList);
			request.getRequestDispatcher("/WEB-INF/jsp/home.jsp").forward(request, response);
		} else {
			List<String> errorMessages = new ArrayList<>();
			errorMessages.add("ログインをしてください。");
			session.setAttribute("errorMessages", errorMessages);
			request.getRequestDispatcher("index.jsp").forward(request, response);
		}
	}

}

src/takamatsu_tatsumi/controllor/PostServlet.java
package takamatsu_tatsumi.controllor;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import takamatsu_tatsumi.beans.Post;
import takamatsu_tatsumi.beans.User;
import takamatsu_tatsumi.service.PostService;
import takamatsu_tatsumi.utils.CheckUtil;

@WebServlet(urlPatterns = {"/newPost"})
public class PostServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		User loginUser = (User) session.getAttribute("loginUser");

		if(loginUser != null) {
			request.getRequestDispatcher("/WEB-INF/jsp/post.jsp").forward(request, response);
		} else {
			List<String> messages = new ArrayList<>();
			messages.add("ログインしてください");
			session.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("login").forward(request, response);
			return;
		}
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		User loginUser = (User) session.getAttribute("loginUser");
		Post newPost = new Post();

		newPost.setTitle(request.getParameter("title"));
		newPost.setText(request.getParameter("postText"));
		newPost.setCategory(request.getParameter("category"));
		newPost.setWritterId(loginUser.getId());

		List<String> messages = new ArrayList<>();
		messages = CheckUtil.isOKPost(messages, newPost);
		if(messages.isEmpty()) {
			PostService postService = new PostService();
			postService.insert(newPost);

			request.getRequestDispatcher("home").forward(request, response);
		} else {
			session.setAttribute("errorMessages", messages);
			session.setAttribute("newPost", newPost);

			doGet(request, response);
		}
	}

}

src/takamatsu_tatsumi/controllor/SettingServlet.java
package takamatsu_tatsumi.controllor;
import static takamatsu_tatsumi.utils.CheckUtil.*;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import takamatsu_tatsumi.beans.Branch;
import takamatsu_tatsumi.beans.Department;
import takamatsu_tatsumi.beans.User;
import takamatsu_tatsumi.service.BranchService;
import takamatsu_tatsumi.service.DepartmentService;
import takamatsu_tatsumi.service.UserService;;

@WebServlet(urlPatterns = {"/settings"})
public class SettingServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();

		User loginUser = (User) session.getAttribute("loginUser");

		if(loginUser != null && loginUser.getDepartmentCode().equals("総務人事担当者")) {
			List<Branch> branchList = new BranchService().getBranchList();
			List<Department> departmentList = new DepartmentService().getDepartmentList();

			String userIdString = request.getParameter("id");
			User editUser = new User();
			if(userIdString != null) {
				int userId = Integer.parseInt(userIdString);
				editUser.setId(userId);
				editUser = new UserService().getEditUser(editUser);
			} else {
				editUser = (User) session.getAttribute("editUser");
			}

			session.setAttribute("editUser", editUser);
			session.setAttribute("branchList", branchList);
			session.setAttribute("departmentList", departmentList);

			request.getRequestDispatcher("/WEB-INF/jsp/settings.jsp").forward(request, response);
		} else {
			List<String> messages = new ArrayList<>();
			messages.add("権限を持っていないためユーザー管理を利用することができません");
			request.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("home").forward(request, response);
		}
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		List<String> messages = new ArrayList<String>();
		User editUser = getUser(request);

		messages = isValid(messages, editUser, false);
		if(messages.isEmpty()) {
			new UserService().update(editUser);
			session.removeAttribute("editUser");
			request.getRequestDispatcher("UserManagement").forward(request, response);
			return;
		} else {
			session.setAttribute("errorMessages", messages);
			session.setAttribute("editUser", editUser);
            doGet(request, response);
		}
	}

	private User getUser (HttpServletRequest request) {
		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setLoginId(request.getParameter("loginId"));
		editUser.setPassword(request.getParameter("password"));
		editUser.setRepassword(request.getParameter("repassword"));
		editUser.setName(request.getParameter("name"));
		editUser.setBranchCode(request.getParameter("branchCode"));
		editUser.setDepartmentCode(request.getParameter("departmentCode"));
		editUser.setStopped(Boolean.parseBoolean(request.getParameter("stopped")));
		return editUser;
	}
}

src/takamatsu_tatsumi/controllor/SignUpServlet.java
package takamatsu_tatsumi.controllor;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import takamatsu_tatsumi.beans.Branch;
import takamatsu_tatsumi.beans.Department;
import takamatsu_tatsumi.beans.User;
import takamatsu_tatsumi.service.BranchService;
import takamatsu_tatsumi.service.DepartmentService;
import takamatsu_tatsumi.service.UserService;
import takamatsu_tatsumi.utils.CheckUtil;


@WebServlet(urlPatterns = {"/signup"})
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		List<Branch> branchList = new BranchService().getBranchList();
		List<Department> departmentList = new DepartmentService().getDepartmentList();

		HttpSession session = request.getSession();

		session.setAttribute("branchList", branchList);
		session.setAttribute("departmentList", departmentList);

		request.getRequestDispatcher("/WEB-INF/jsp/signup.jsp").forward(request, response);
		return;
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		User loginUser = (User) session.getAttribute("loginUser");

		if(loginUser != null && loginUser.getDepartmentCode().equals("総務人事担当者")) {
			User newUser = getUser(request);

			List<String> messages = new ArrayList<String>();
			messages = CheckUtil.isValid(messages, newUser, true);

			if(!messages.isEmpty()) {
				session.setAttribute("errorMessages", messages);
				session.setAttribute("newUser", newUser);
				response.sendRedirect("signup");
				return;
			}

			new UserService().register(newUser, messages);
			session.removeAttribute("newUser");
			request.getRequestDispatcher("UserManagement").forward(request, response);
			return;

		} else {
			List<String> messages = new ArrayList<>();
			messages.add("権限を持っていないためユーザー管理を利用することができません");
			request.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("home").forward(request, response);
			return;
		}
	}

	private User getUser (HttpServletRequest request) {
		User newUser = new User();
		newUser.setLoginId(request.getParameter("loginId"));
		newUser.setPassword(request.getParameter("password"));
		newUser.setRepassword(request.getParameter("repassword"));
		newUser.setName(request.getParameter("name"));
		newUser.setBranchCode(request.getParameter("branchCode"));
		newUser.setDepartmentCode(request.getParameter("departmentCode"));
		newUser.setStopped(false);
		return newUser;
	}
}

src/takamatsu_tatsumi/controllor/UserManagementServlet.java
package takamatsu_tatsumi.controllor;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import takamatsu_tatsumi.beans.User;
import takamatsu_tatsumi.service.UserService;

@WebServlet("/UserManagement")
public class UserManagementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute("loginUser");

		if(user != null && user.getDepartmentCode().equals("総務人事担当者")) {
			List<User> userList = new UserService().getUserList(user);
			request.setAttribute("userList", userList);
			request.getRequestDispatcher("/WEB-INF/jsp/UserManagement.jsp").forward(request, response);
		} else {
			List<String> messages = new ArrayList<>();
			messages.add("権限を持っていないためユーザー管理を利用することができません");
			request.setAttribute("errorMessages", messages);
			request.getRequestDispatcher("home").forward(request, response);
		}
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

}

WebContent/WEB-INF/jsp/UserManagement.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link href="./css/style.css" rel="stylesheet" type="text/css">
<title>ユーザー管理画面</title>
</head>
<body>
<script>
	function alertFunction1(message, id) {
		if(confirm("ユーザーを" + message + "してもいいですか？")){
			var str = "stopped?stoppedId=" + id;
			window.location.href = str;
		} else {
			alert( "データの送信をキャンセルします。") ;
		}
	}
</script>
<div class="main-content">
	<a href="signup">ユーザー新規作成</a>　　　<a href="home">戻る</a>
	<div class="title">ユーザー一覧</div>
	<div class="userList">
			<table>
				<tr><th>id</th><th>名前</th><th>ログインID</th><th>所属</th><th>役職・部署</th><th>登録日</th><th>アカウント状態</th></tr>
				<c:forEach items="${userList}" var="editUser">
					<tr>
						<td><a href="<c:url value="settings"><c:param name="id" value="${ editUser.id }" /></c:url>" >${ editUser.id }</a></td>
						<td>${ editUser.name }</td>
						<td>${ editUser.loginId }</td>
						<td>${ editUser.branchCode }</td>
						<td>${ editUser.departmentCode }</td>
						<td>${ editUser.createdDate }</td>
						<td><button onclick="alertFunction1('${editUser.stopped ? '稼働' : '停止'}', '${editUser.id}')" >${ editUser.stopped ? "停止" : "稼働" }</button></td>
					</tr>
				</c:forEach>
			</table>
	</div>
	<a href="signup">ユーザー新規作成</a>　　　<a href="home">戻る</a>
</div>
</body>
</html>

WebContent/WEB-INF/jsp/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link href="./css/style.css" rel="stylesheet" type="text/css">
<title>ホーム</title>
</head>
<body>
<script>
	function postDeleteFunction(id) {
		if(confirm("この投稿を削除してもいいですか？")){
			var url = "postDelete?postDelete=" + id;
			window.location.href = url;
		} else {
			alert( "削除をキャンセルしました。") ;
		}
	}

	function commentDeleteFunction(id) {
		if(confirm("このコメントを削除してもいいですか？")){
			var url = "commentDelete?commentDelete=" + id;
			window.location.href = url;
		} else {
			alert( "削除をキャンセルしました。") ;
		}
	}

	function commentListDisp(id) {
		obj=document.getElementById('commentList' + id).style;
		obj.display=(obj.display=='none')?'block':'none';
	}
</script>
	<div class="main-contants">
		<a href="UserManagement">ユーザー管理</a> <a href="newPost">新規投稿</a> <a href="logout">ログアウト</a> <div class="loginUser">ログインユーザー：${loginUser.name}さん</div>
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>
		<div class="posts">
			<div class="searchform">
				<form action="search" method="post">
					<div class="categorySerch">カテゴリー検索：<input type="text" name="searchWord" id="searchWord" placeholder="検索ワードを入れてください"/><br /></div>
					日付検索：
					<input type="text" name="beforeYear" id="beforeYear" placeholder="年度" value="${dateFormat.beforeYear}"/>年
					<input type="text" name="beforeMouth" id="beforeMouth" placeholder="月" value="${dateFormat.beforeMouth}"/>月
					<input type="text" name="beforeDay" id="beforeDay" placeholder="日" value="${dateFormat.beforeDay}"/>日
					～
					<input type="text" name="afterYear" id="afterYear" placeholder="年度" value="${dateFormat.afterYear}"/>年
					<input type="text" name="afterMouth" id="afterMouth" placeholder="月" value="${dateFormat.afterMouth}"/>月
					<input type="text" name="afterDay" id="afterDay" placeholder="日" value="${dateFormat.afterDay}"/>日
					<button type="submit">検索</button>
				</form>
			</div>
			<c:forEach items="${postList}" var="post">
				<c:if test="${!post.delete}" >
					<div class= "post">
						title: ${post.title}<br />
						${post.text}<br />
						<div class="writer">
							投稿者：${post.writterName} 投稿日：${post.createdDate} カテゴリー：${post.category}<br />
							<c:if test="${post.writterId.equals(loginUser.id)}">
								<button onclick="postDeleteFunction('${post.id}')" >削除</button>
							</c:if>
						</div>
					</div>

					<div class="comment">
						<div onclick=commentListDisp(${post.id})>
							<a style="cursor:pointer;">▶コメント一覧</a>
						</div>
						<div id="commentList${post.id}" style="display:none; clear:both;">
							<c:forEach items="${post.comments}" var="comment">
								<c:if test="${!comment.delete}" >
									<h4>${comment.text}</h4><br />
									<div class="writer">${comment.writterName} : ${comment.createdDate}<br />
										<c:if test="${comment.writterId.equals(loginUser.id)}">
											<button onclick="commentDeleteFunction('${comment.id}')" >削除</button>
										</c:if>
									</div>
								</c:if>
							</c:forEach>
							<form action="commentpost" method="post">
								<textarea name="comment" id="comment" rows="" cols="" placeholder="500字以内で入力して下さい。" ></textarea>
								<input type="hidden" name="postId" id="postId" value="${post.id}" />
								<button type="submit">コメント</button>
							</form>
						</div>
					</div>
				</c:if>
			</c:forEach>
		</div>
	</div>
</body>
</html>

WebContent/WEB-INF/jsp/post.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ page isELIgnored="false" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<link href="./css/style.css" rel="stylesheet" type="text/css">
<meta charset="UTF-8">
<title>新規投稿</title>
</head>
<body>
	<div class="main-contants">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>
		<div class="inputfrom">
			<form action="newPost" method="post">
				<label for="title">タイトル</label><input type="text" id="title" name="title" value="${newPost.title}" placeholder="30字以内で入力してください"/><br />
				<label for="postText">本文</label><textarea name="postText"id="postText" rows="" cols="" placeholder="1000字以内で入力してください">${newPost.text}</textarea><br />
				<label for="category">カテゴリー</label><input type="text" id="category" name="category" value="${newPost.category}" placeholder="10字以内で入力してください"/><br />
				<br /><div class="submits"><button type="submit">投稿</button>　　　　　<a href="home">戻る</a></div>
			</form>
		</div>
	</div>
</body>
</html>

WebContent/WEB-INF/jsp/settings.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<link href="./css/style.css" rel="stylesheet" type="text/css">
<meta charset="UTF-8">
<title>ユーザー設定</title>
</head>
<body>
<div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
            <div class="inputfrom">
	            <form action="settings" method="post">
	                <br />

		                <input name="id" id="id" value="${editUser.id }" type="hidden" />
		                <label for="name">名前</label> <input name="name" id="name" value="${editUser.name}" />（名前はあなたの公開プロフィールに表示されます）<br />
		                <label for="loginId">ログインID</label> <input name="loginId"id="loginId" value="${editUser.loginId}" /> <br />
		                <label for="password">パスワード</label> <input name="password" type="password" id="password" /> <br />
		                <label for="repassword">確認用パスワード</label> <input name="repassword" type="password" id="repassword" /> <br />
		                <label for="branchCode">支店</label> <select name="branchCode" id="branchCode">
		                    <c:forEach items="${branchList}" var="branch">
		                    	<c:set var="branchName" value="${branch.name}" />
		                		<option value="${ branch.name }" ${ not empty editUser.branchCode && editUser.branchCode.equals(branchName) ? " selected=\"selected\"" : ""}>${ branch.name }</option>
		                	</c:forEach>
		                </select><br />
		                <label for="departmentCode">部署・役職</label> <select name="departmentCode" id="departmentCode">
		                    <c:forEach items="${departmentList}" var="department">
		                    	<c:set var="departmentName" value="${department.name}" />
		                		<option value="${ department.name }" ${ not empty editUser.branchCode && editUser.departmentCode.equals(departmentName) ? " selected=\"selected\"" : ""}>${ department.name }</option>
		                	</c:forEach>
		                </select><br />
		                <label for="isStopped">アカウント状態：</label>${editUser.stopped ? "停止" : "稼働中"}<input name="stopped" id="stopped" value="${editUser.stopped }" type="hidden" />

	                	<br /><div class="submits"><button type="submit">変更</button>　　　　　<a href="UserManagement">戻る</a></div>

	            </form>
            </div>
            <div class="copyright">Copyright(c)takamatsu</div>
        </div>
</body>
</html>

WebContent/WEB-INF/jsp/signup.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href="./css/style.css" rel="stylesheet" type="text/css">
    <title>ユーザー登録</title>
    </head>
    <body>
        <div class="main-contents">
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session" />
            </c:if>
            <div class="inputfrom">
	            <form action="signup" method="post">
	                <br />
	                <label for="name">名前</label> <input name="name" id="name" value="${newUser.name}" />（名前はあなたの公開プロフィールに表示されます）<br />
	                <label for="loginId">ログインID</label> <input name="loginId"id="loginId" value="${newUser.loginId}" /> <br />
	                <label for="password">パスワード</label> <input name="password" type="password" id="password" /> <br />
	                <label for="repassword">確認用パスワード</label> <input name="repassword" type="password" id="repassword" /> <br />
	                <label for="branchCode">支店</label> <select name="branchCode" id="branchCode">
	                	<option value="">選択してください</option>
	                	<c:forEach items="${branchList}" var="branch">
	                		<c:set var="branchName" value="${branch.name}" />
	                		<option value="${ branch.name }" ${ not empty newUser.branchCode && newUser.branchCode.equals(branchName) ? " selected=\"selected\"" : ""}>${ branch.name }</option>
	                	</c:forEach>
	                </select><br />
	                <label for="departmentCode">部署・役職</label> <select name="departmentCode" id="departmentCode">
	                	<option value="">選択してください</option>
	                	<c:forEach items="${departmentList}" var="department">
	                		<c:set var="departmentName" value="${department.name}" />
	                		<option value="${ department.name }" ${ not empty newUser.branchCode != null && newUser.departmentCode.equals(departmentName) ? " selected=\"selected\"" : ""}>${ department.name }</option>
	                	</c:forEach>
	                </select><br />
	                <br /><div class = "submits"><button type="submit">登録</button>　　　　　<a href="UserManagement">戻る</a></div>
	            </form>
            </div>
            <div class="copyright">Copyright(c)takamatsu</div>
        </div>
    </body>
</html>